[package]
name = "hello"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../../lib" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonrpc-v2 = "0.10"
tokio = { version = "1", features = ["full"] }
